//
//  GameLog.h
//  BaseballQuery
//
//  Created by Mark Knopper on 6/9/11.
//  Copyright (c) 2011 Bulbous Ventures LLC. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>


@interface GameLog : NSManagedObject {
@private
}
@property (nonatomic) NSString * acquisitionInfo;
@property (nonatomic) NSString * additionalInfo;
@property (nonatomic) NSNumber * attendance;
@property (nonatomic) NSString * completion;
@property (nonatomic) NSDate * date;
@property (nonatomic) NSString * dayOfWeek;
@property (nonatomic) NSString * dayOrNight;
@property (nonatomic) NSString * firstBaseUmpireID;
@property (nonatomic) NSString * firstBaseUmpireName;
@property (nonatomic) NSString * forfeitInfo;
@property (nonatomic) NSString * gameWinningRBIBatterID;
@property (nonatomic) NSString * gameWinningRBIBatterName;
@property (nonatomic) NSNumber * home2B;
@property (nonatomic) NSNumber * home3B;
@property (nonatomic) NSNumber * homeA;
@property (nonatomic) NSNumber * homeAB;
@property (nonatomic) NSNumber * homeAFOCI;
@property (nonatomic) NSString * homeBatter1ID;
@property (nonatomic) NSString * homeBatter1Name;
@property (nonatomic) NSNumber * homeBatter1Pos;
@property (nonatomic) NSString * homeBatter2ID;
@property (nonatomic) NSString * homeBatter2Name;
@property (nonatomic) NSNumber * homeBatter2Pos;
@property (nonatomic) NSString * homeBatter3ID;
@property (nonatomic) NSString * homeBatter3Name;
@property (nonatomic) NSNumber * homeBatter3Pos;
@property (nonatomic) NSString * homeBatter4ID;
@property (nonatomic) NSString * homeBatter4Name;
@property (nonatomic) NSNumber * homeBatter4Pos;
@property (nonatomic) NSString * homeBatter5ID;
@property (nonatomic) NSString * homeBatter5Name;
@property (nonatomic) NSNumber * homeBatter5Pos;
@property (nonatomic) NSString * homeBatter6ID;
@property (nonatomic) NSString * homeBatter6Name;
@property (nonatomic) NSNumber * homeBatter6Pos;
@property (nonatomic) NSString * homeBatter7ID;
@property (nonatomic) NSString * homeBatter7Name;
@property (nonatomic) NSNumber * homeBatter7Pos;
@property (nonatomic) NSString * homeBatter8ID;
@property (nonatomic) NSString * homeBatter8Name;
@property (nonatomic) NSNumber * homeBatter8Pos;
@property (nonatomic) NSString * homeBatter9ID;
@property (nonatomic) NSString * homeBatter9Name;
@property (nonatomic) NSNumber * homeBatter9Pos;
@property (nonatomic) NSNumber * homeBB;
@property (nonatomic) NSNumber * homeBK;
@property (nonatomic) NSNumber * homeCS;
@property (nonatomic) NSNumber * homeDP;
@property (nonatomic) NSNumber * homeE;
@property (nonatomic) NSNumber * homeGIDP;
@property (nonatomic) NSNumber * homeH;
@property (nonatomic) NSNumber * homeHBP;
@property (nonatomic) NSNumber * homeHR;
@property (nonatomic) NSNumber * homeIBB;
@property (nonatomic) NSNumber * homeIndividualER;
@property (nonatomic) NSString * homeLineScore;
@property (nonatomic) NSNumber * homeLOB;
@property (nonatomic) NSString * homeManagerID;
@property (nonatomic) NSString * homeManagerName;
@property (nonatomic) NSNumber * homePB;
@property (nonatomic) NSNumber * homePitchersUsed;
@property (nonatomic) NSString * homePlateUmpireID;
@property (nonatomic) NSString * homePlateUmpireName;
@property (nonatomic) NSNumber * homePO;
@property (nonatomic) NSNumber * homeRBI;
@property (nonatomic) NSNumber * homeSB;
@property (nonatomic) NSNumber * homeScore;
@property (nonatomic) NSNumber * homeSF;
@property (nonatomic) NSNumber * homeSH;
@property (nonatomic) NSNumber * homeSO;
@property (nonatomic) NSString * homeStartingPitcherID;
@property (nonatomic) NSString * homeStartingPitcherName;
@property (nonatomic) NSNumber * homeTeamER;
@property (nonatomic) NSNumber * homeTeamGameNum;
@property (nonatomic) NSString * homeTeamID;
@property (nonatomic) NSString * homeTeamLeague;
@property (nonatomic) NSNumber * homeTP;
@property (nonatomic) NSNumber * homeWP;
@property (nonatomic) NSNumber * lengthOfGameInOuts;
@property (nonatomic) NSString * LFUmpireID;
@property (nonatomic) NSString * LFUmpireName;
@property (nonatomic) NSString * losingPitcherID;
@property (nonatomic) NSString * losingPitcherName;
@property (nonatomic) NSNumber * numberOfGame;
@property (nonatomic) NSString * parkID;
@property (nonatomic) NSString * protestInfo;
@property (nonatomic) NSString * RFUmpireID;
@property (nonatomic) NSString * RFUmpireName;
@property (nonatomic) NSString * savingPitcherID;
@property (nonatomic) NSString * savingPitcherName;
@property (nonatomic) NSString * secondBaseUmpireID;
@property (nonatomic) NSString * secondBaseUmpireName;
@property (nonatomic) NSString * thirdBaseUmpireID;
@property (nonatomic) NSString * thirdBaseUmpireName;
@property (nonatomic) NSNumber * timeOfGameInMinutes;
@property (nonatomic) NSNumber * visiting2B;
@property (nonatomic) NSNumber * visiting3B;
@property (nonatomic) NSNumber * visitingA;
@property (nonatomic) NSNumber * visitingAB;
@property (nonatomic) NSNumber * visitingAFOCI;
@property (nonatomic) NSString * visitingBatter1ID;
@property (nonatomic) NSString * visitingBatter1Name;
@property (nonatomic) NSNumber * visitingBatter1Pos;
@property (nonatomic) NSString * visitingBatter2ID;
@property (nonatomic) NSString * visitingBatter2Name;
@property (nonatomic) NSNumber * visitingBatter2Pos;
@property (nonatomic) NSString * visitingBatter3ID;
@property (nonatomic) NSString * visitingBatter3Name;
@property (nonatomic) NSString * visitingBatter3Pos;
@property (nonatomic) NSString * visitingBatter4ID;
@property (nonatomic) NSString * visitingBatter4Name;
@property (nonatomic) NSNumber * visitingBatter4Pos;
@property (nonatomic) NSString * visitingBatter5ID;
@property (nonatomic) NSString * visitingBatter5Name;
@property (nonatomic) NSNumber * visitingBatter5Pos;
@property (nonatomic) NSString * visitingBatter6ID;
@property (nonatomic) NSString * visitingBatter6Name;
@property (nonatomic) NSNumber * visitingBatter6Pos;
@property (nonatomic) NSString * visitingBatter7ID;
@property (nonatomic) NSString * visitingBatter7Name;
@property (nonatomic) NSNumber * visitingBatter7Pos;
@property (nonatomic) NSString * visitingBatter8ID;
@property (nonatomic) NSString * visitingBatter8Name;
@property (nonatomic) NSString * visitingBatter8Pos;
@property (nonatomic) NSString * visitingBatter9ID;
@property (nonatomic) NSString * visitingBatter9Name;
@property (nonatomic) NSNumber * visitingBatter9Pos;
@property (nonatomic) NSNumber * visitingBB;
@property (nonatomic) NSNumber * visitingBK;
@property (nonatomic) NSNumber * visitingCS;
@property (nonatomic) NSNumber * visitingDP;
@property (nonatomic) NSNumber * visitingE;
@property (nonatomic) NSNumber * visitingGIDP;
@property (nonatomic) NSNumber * visitingH;
@property (nonatomic) NSNumber * visitingHBP;
@property (nonatomic) NSNumber * visitingHR;
@property (nonatomic) NSNumber * visitingIBB;
@property (nonatomic) NSNumber * visitingIndividualER;
@property (nonatomic) NSString * visitingLineScore;
@property (nonatomic) NSNumber * visitingLOB;
@property (nonatomic) NSString * visitingManagerID;
@property (nonatomic) NSString * visitingManagerName;
@property (nonatomic) NSNumber * visitingPB;
@property (nonatomic) NSNumber * visitingPitchersUsed;
@property (nonatomic) NSNumber * visitingPO;
@property (nonatomic) NSNumber * visitingRBI;
@property (nonatomic) NSNumber * visitingSB;
@property (nonatomic) NSNumber * visitingScore;
@property (nonatomic) NSNumber * visitingSF;
@property (nonatomic) NSNumber * visitingSH;
@property (nonatomic) NSNumber * visitingSO;
@property (nonatomic) NSString * visitingStartingPitcherID;
@property (nonatomic) NSString * visitingStartingPitcherName;
@property (nonatomic) NSNumber * visitingTeamER;
@property (nonatomic) NSNumber * visitingTeamGameNum;
@property (nonatomic) NSString * visitingTeamID;
@property (nonatomic) NSString * visitingTeamLeague;
@property (nonatomic) NSNumber * visitingTP;
@property (nonatomic) NSNumber * visitingWP;
@property (nonatomic) NSString * winningPitcherID;
@property (nonatomic) NSString * winningPitcherName;

@end
